include:
  - remote: 'https://gitlab.gnome.org/Infrastructure/freedesktop-ci-templates/-/raw/e195d80f35b45cc73668be3767b923fd76c70ed5/templates/fedora.yml'
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      job-stage: release
      dist-job-name: "fedora-build"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

variables:
  DEPENDENCIES:
    gcc
    git
    meson
    glibc-devel
    glib2-devel
    upower-devel
    gtk4-devel
    gettext
  MESON_BUILD_DIR: _build
  TARBALL_ARTIFACT_PATH: "${MESON_BUILD_DIR}/meson-dist/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

stages:
  - image
  - build
  - release

workflow:
  rules:
    # run merge request pipelines, for main or release branches and for manually
    # triggered pipelines (source "web"), but not for translation updates
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event" ||
           $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED ||
           $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ||
           $CI_COMMIT_BRANCH =~ /^gnome-.*$/ ||
           $CI_PIPELINE_SOURCE == "web") &&
          $CI_COMMIT_TITLE !~ /^Update.*translation$/


.gnome-power-manager.fedora:
  variables:
    FDO_DISTRIBUTION_VERSION: 41
    FDO_DISTRIBUTION_TAG: '2025-01-03.1'

build-fedora-image:
  extends:
  - .fdo.container-build@fedora
  - .gnome-power-manager.fedora
  stage: image
  variables:
    FDO_DISTRIBUTION_PACKAGES: $DEPENDENCIES

fedora-build:
  extends:
  - .fdo.distribution-image@fedora
  - .gnome-power-manager.fedora
  stage: build
  before_script:
    - cc -v
  script:
    - meson setup ${MESON_BUILD_DIR}
    - meson dist -C ${MESON_BUILD_DIR}
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}"
    when: always
    paths:
      - "${CI_PROJECT_DIR}/${MESON_BUILD_DIR}/meson-logs"
      - "${CI_PROJECT_DIR}/${MESON_BUILD_DIR}/meson-dist"
      - "${TARBALL_ARTIFACT_PATH}"
    expire_in: 14 days
